### ISSUE TITLE
Loading Error - Page Down °Urgent Fix!

### ISSUE THREAD

**Issue by Algorithmic-User** [Weaverse/pilot#203]
Because when we enter the Pilot template page, it takes a while to load and the following message appears "We found an error while loading this page."

**Comment by paul-phan** [comment]
Hi @Algorithmic-User,

I apologize for the recent issue you experienced. It appears that there was a network connection issue from our service provider, but it has been resolved within a few minutes. Could you please check again and let us know if the problem has been fixed?

Regards,
Paul
